spring.application.name=faq
server.port=8000

# Настройки подключения к БД (Postgres)
spring.datasource.url=jdbc:postgresql://77.232.132.223:5432/faq_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Настройки JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.session.jdbc.initialize-schema=always

# Настройки Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Настройки Swagger / OpenAPI
# Сваггер будет доступен по адресу: http://localhost:8080/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
# Настройка пользователя для входа (Security)
spring.security.user.name=admin
spring.security.user.password=admin123